-- liquibase formatted sql

-- changeset Alexey_Bobrovich:1753614578907-1
CREATE TABLE token_table (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, access_token VARCHAR(255), refresh_token VARCHAR(255), is_logged_out BOOLEAN, user_id BIGINT, CONSTRAINT pk_token_table PRIMARY KEY (id));

-- changeset Alexey_Bobrovich:1753614578907-2
CREATE TABLE users_table (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255), email VARCHAR(255), password VARCHAR(255), first_name VARCHAR(255), last_name VARCHAR(255), role VARCHAR(255), CONSTRAINT pk_users_table PRIMARY KEY (id));

-- changeset Alexey_Bobrovich:1753614578907-3
ALTER TABLE token_table ADD CONSTRAINT FK_TOKEN_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES users_table (id);

